import { randomBytes } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { isAbsolute, join, relative, resolve } from "node:path";
import type { LocalTool, ToolContext, ToolResult, ToolUpdate } from "./types.js";
import { defineTool } from "./types.js";
import type { ToolProvider } from "./capability-registry.js";
import { detectImageMime } from "./util.js";

/**
 * Provider-agnostic media/image generation tools.
 *
 * Ported from Nexus's image-gen / media-gen tool providers and reduced to a
 * single OpenAI-compatible HTTP shape per modality. Each modality is enabled by
 * configuring an endpoint + apiKey + model; when a modality is not configured
 * the tool returns a clear error result (it never throws) instructing the
 * operator to configure an endpoint. The provider as a whole is hidden from the
 * registry when `enabled` is false.
 *
 * Generated bytes are written to a hidden "<outputDir>/.nexus-media/" dir and
 * the absolute path + mimeType + byteSize are returned.
 */

const MEDIA_DIR = ".nexus-media";
const DEFAULT_TIMEOUT_MS = 120_000;
const DEFAULT_POLL_INTERVAL_MS = 5_000;

/** Image-to-image / image-to-video reference constants (ported from image-gen). */
const MAX_REFERENCE_IMAGE_BYTES = 10 * 1024 * 1024;
const REFERENCE_MIME_TYPES = new Set(["image/png", "image/jpeg", "image/webp"]);
const DEFAULT_MAX_REFERENCE_IMAGES = 4;
/** Aspect ratios accepted by generate_image; mapped to a WxH via {@link mapImageSize}. */
const ASPECT_RATIOS = new Set(["1:1", "4:3", "3:4", "16:9", "9:16", "3:2", "2:3", "21:9"]);
/** Long-edge pixel tiers selectable via image_size. */
const SIZE_TIERS: Record<string, number> = { "1K": 1024, "2K": 2048 };
const SIZE_STEP = 64;
const MIN_EDGE = 256;
/** Resolutions accepted by generate_video (ported from media-gen). */
const VIDEO_RESOLUTIONS = ["768P", "1080P"];
/** Audio container formats accepted by generate_speech / generate_music. */
const AUDIO_FORMATS = ["mp3", "wav", "flac", "pcm", "pcm16"] as const;

export interface MediaEndpointConfig {
  endpoint?: string;
  apiKey?: string;
  model?: string;
  /**
   * Optional vendor wire-shape selector (faithful to the original capabilities
   * `*GenerationProtocol`). Empty / omitted / unknown keeps the OpenAI-compatible
   * default path so existing configs are unaffected. Recognized values per
   * modality:
   *   - image:  "openai-images" | "async-image"
   *   - speech: "openai-speech" | "async-t2a" | "mimo-tts"
   *   - music:  "async-music"
   *   - video:  "async-video"
   */
  protocol?: string;
  /**
   * Optional default `WxH` size threaded into {@link mapImageSize} as the
   * fallback when neither aspect_ratio nor image_size is supplied (image
   * provider only). Mirrors the original image-gen `config.defaultSize`.
   */
  defaultSize?: string;
  /** Speech: default provider voice id/name used when the tool-call omits one. */
  voice?: string;
  /** Speech/Music: default audio container format used when the tool-call omits one. */
  format?: string;
  /** Video: default clip duration (seconds) used when the tool-call omits one. */
  defaultDuration?: number;
  /** Video: default resolution tier used when the tool-call omits one. */
  defaultResolution?: string;
  /** Per-modality request timeout budget in ms (falls back to DEFAULT_TIMEOUT_MS). */
  timeoutMs?: number;
}

/**
 * Minimal structural view of the attachment store used to create inline image
 * previews. The real {@link AttachmentStore} satisfies this via its `put`
 * method; when no store is supplied (the default) inline previews are skipped
 * with a warning, keeping the capability inert by default.
 */
export interface MediaAttachmentStore {
  put(input: {
    name: string;
    data: Buffer;
    mimeType?: string;
    threadId?: string;
    workspace?: string;
  }): Promise<{ id: string; name: string; mimeType: string; width?: number; height?: number }>;
}

export interface MediaProviderConfig {
  enabled?: boolean;
  image?: MediaEndpointConfig;
  speech?: MediaEndpointConfig;
  music?: MediaEndpointConfig;
  video?: MediaEndpointConfig;
  outputDir: string;
  /** Optional: maximum reference images accepted for image-to-image (default 4). */
  maxReferenceImages?: number;
  /** Optional: store for inline image previews. When absent, previews are skipped. */
  attachmentStore?: MediaAttachmentStore;
}

export function buildMediaToolProvider(config: MediaProviderConfig): ToolProvider {
  const enabled = Boolean(config.enabled);
  const outputDir = config.outputDir;
  const maxReferenceImages = config.maxReferenceImages ?? DEFAULT_MAX_REFERENCE_IMAGES;

  const tools: LocalTool[] = [
    buildImageTool(config.image, outputDir, maxReferenceImages, config.attachmentStore),
    buildSpeechTool(config.speech, outputDir),
    buildMusicTool(config.music, outputDir),
    buildVideoTool(config.video, outputDir),
  ];

  if (!enabled) {
    return {
      id: "media",
      kind: "media",
      enabled: false,
      available: false,
      reason: "media generation is disabled",
      tools: [],
    };
  }

  return {
    id: "media",
    kind: "media",
    enabled: true,
    available: true,
    tools,
  };
}

// --- image-generation SERVICE seam (write infographic, etc.) -----------------

/**
 * Result of a one-shot image generation via {@link ImageGenerationService}.
 * Mirrors {@link MediaFileResult} (a hidden `<outputDir>/.nexus-media/` file)
 * with the generated dimensions folded in when sniffable.
 */
export interface ImageGenerationResult {
  /** Path under the output dir (e.g. `.nexus-media/img-….png`). */
  relativePath: string;
  absolutePath: string;
  mimeType: string;
  byteSize: number;
  width?: number;
  height?: number;
  /** The size string actually sent to the provider (when one was resolved). */
  size?: string;
  model: string;
}

/**
 * A thin, service-callable image-generation seam over the SAME private HTTP +
 * file-write helpers the `generate_image` agent tool uses (`requestImageGenerate`
 * / `requestAsyncImage` → `writeMediaFile`). It exists so non-agent callers
 * (the Write surface's infographic action, T5.x) can rasterize a prompt without
 * going through the tool registry.
 *
 * `available` reflects the live image config (endpoint + apiKey + model present);
 * a route can gate a clean 503 on it. `generate` POSTs a text-to-image request
 * and writes the bytes to the hidden media dir, throwing a typed
 * {@link ImageGenerationError} (carrying a provider status when known) on
 * failure so the caller can surface a 400 rather than a 500.
 */
export interface ImageGenerationService {
  /** True when endpoint + apiKey + model are all configured. */
  readonly available: boolean;
  /** The configured model id (empty string when unavailable). */
  readonly model: string;
  generate(input: {
    prompt: string;
    /** Optional explicit `WxH`; falls back to the provider's configured defaultSize. */
    size?: string;
    signal?: AbortSignal;
  }): Promise<ImageGenerationResult>;
}

/** Typed image-generation failure carrying an optional upstream HTTP status. */
export class ImageGenerationError extends Error {
  constructor(
    message: string,
    /** Upstream provider HTTP status when the failure came from the provider. */
    readonly status?: number,
  ) {
    super(message);
    this.name = "ImageGenerationError";
  }
}

/**
 * Build an {@link ImageGenerationService} bound to an image media config and an
 * output dir. Reuses the module-private provider helpers, so the wire-shape,
 * `response_format` retry, URL-download fallback, Async branch, and the
 * `.nexus-media/` file layout are byte-identical to the `generate_image` tool.
 */
export function buildImageGenerationService(
  image: MediaEndpointConfig | undefined,
  outputDir: string,
): ImageGenerationService {
  const cfg = resolveConfig(image);
  return {
    available: cfg !== null,
    model: cfg?.model ?? "",
    async generate(input) {
      if (!cfg) {
        throw new ImageGenerationError(
          "image generation is not configured; set an endpoint, apiKey, and model for the image media provider",
        );
      }
      const prompt = pickString(input.prompt);
      if (!prompt) throw new ImageGenerationError("prompt is required");
      // Explicit size wins; otherwise fall back to the provider's defaultSize.
      const size = pickString(input.size) ?? mapImageSize(undefined, undefined, pickString(image?.defaultSize));
      const signal = withTimeout(input.signal ?? new AbortController().signal, resolveTimeoutMs(image));
      try {
        const generated =
          cfg.protocol === "async-image"
            ? await requestAsyncImage(cfg, { prompt, ...(size ? { size } : {}), signal })
            : await requestImageGenerate(cfg, { prompt, ...(size ? { size } : {}), signal });
        let mimeType = generated.mimeType;
        const detected = detectImageDimensions(generated.data);
        if (detected) mimeType = detected.mimeType;
        const file = await writeMediaFile(outputDir, "infographic", imageExtension(mimeType), generated.data, mimeType);
        return {
          relativePath: file.relativePath,
          absolutePath: file.absolutePath,
          mimeType,
          byteSize: file.byteSize,
          ...(detected?.width ? { width: detected.width } : {}),
          ...(detected?.height ? { height: detected.height } : {}),
          ...(size ? { size } : {}),
          model: cfg.model,
        };
      } catch (error) {
        if (error instanceof ImageGenHttpError) throw new ImageGenerationError(error.message, error.status);
        if (error instanceof MediaProviderError) throw new ImageGenerationError(error.message);
        throw new ImageGenerationError(networkErrorMessage(imagesUrl(cfg.endpoint, "generations"), error));
      }
    },
  };
}

// --- generate_image ---------------------------------------------------------

function buildImageTool(
  image: MediaEndpointConfig | undefined,
  outputDir: string,
  maxReferenceImages: number,
  attachmentStore: MediaAttachmentStore | undefined,
): LocalTool {
  return defineTool({
    name: "generate_image",
    description: [
      "Generate an image from a text prompt using the configured OpenAI-compatible images endpoint.",
      "Optionally pass reference_image_paths (image files inside the workspace) to guide the result (image-to-image).",
      "The generated image is written to a hidden media directory and its absolute path is returned.",
      "Generates exactly one image per call; call again for variations.",
    ].join(" "),
    toolKind: "tool_call",
    policy: "untrusted",
    inputSchema: {
      type: "object",
      properties: {
        prompt: { type: "string", description: "Detailed description of the image to generate" },
        size: { type: "string", description: "Optional WxH size, e.g. 1024x1024" },
        aspect_ratio: {
          type: "string",
          enum: [...ASPECT_RATIOS],
          description: "Optional aspect ratio; combined with image_size to derive a WxH size.",
        },
        image_size: {
          type: "string",
          enum: Object.keys(SIZE_TIERS),
          description: "Resolution tier, defaults to 1K",
        },
        reference_image_paths: {
          type: "array",
          items: { type: "string" },
          maxItems: maxReferenceImages,
          description: "Workspace-relative paths of reference images for image-to-image guidance",
        },
      },
      required: ["prompt"],
      additionalProperties: false,
    },
    async execute(args, context) {
      const startedAt = Date.now();
      const cfg = resolveConfig(image);
      if (!cfg) return notConfigured("image");
      const prompt = pickString(args.prompt);
      if (!prompt) return toolError("invalid_prompt", "prompt is required");
      // Explicit `size` wins; otherwise derive from aspect_ratio + image_size.
      const explicitSize = pickString(args.size);
      const aspectRatio = pickString(args.aspect_ratio);
      const imageSize = pickString(args.image_size);
      // Faithful to image-gen-tool-provider.js (~line 127): thread the provider's
      // configured default size as the mapImageSize fallback so a bare prompt
      // still sends a configured size.
      const defaultSize = pickString(image?.defaultSize);
      const size = explicitSize ?? mapImageSize(aspectRatio, imageSize, defaultSize);

      const references = await collectReferenceImages(
        args.reference_image_paths,
        context.workspace,
        maxReferenceImages,
      );
      if ("error" in references) return references.error;
      const endpoint: "edits" | "generations" =
        references.images.length > 0 ? "edits" : "generations";

      const signal = withTimeout(context.abortSignal, resolveTimeoutMs(image));
      try {
        const image_ =
          cfg.protocol === "async-image"
            ? await requestAsyncImage(cfg, {
                prompt,
                size,
                ...(endpoint === "edits" ? { images: references.images } : {}),
                signal,
              })
            : endpoint === "edits"
              ? await requestImageEdit(cfg, { prompt, size, images: references.images, signal })
              : await requestImageGenerate(cfg, { prompt, size, signal });
        let mimeType = image_.mimeType;
        const detected = detectImageDimensions(image_.data);
        if (detected) mimeType = detected.mimeType;
        const file = await writeMediaFile(outputDir, "img", imageExtension(mimeType), image_.data, mimeType);

        // Inline preview: best-effort; never fails the generation.
        const warnings: string[] = [];
        const attachments: Array<Record<string, unknown>> = [];
        if (attachmentStore) {
          try {
            const attachment = await attachmentStore.put({
              name: file.absolutePath.split("/").pop() || "image.png",
              data: image_.data,
              mimeType,
              threadId: context.threadId,
              workspace: context.workspace,
            });
            attachments.push({
              id: attachment.id,
              name: attachment.name,
              mimeType: attachment.mimeType,
              ...(attachment.width ? { width: attachment.width } : {}),
              ...(attachment.height ? { height: attachment.height } : {}),
            });
          } catch (error) {
            warnings.push(`inline preview unavailable: ${errorMessageMedia(error)}`);
          }
        } else {
          warnings.push("inline preview unavailable: attachment store is disabled");
        }

        const fileEntry = {
          ...file,
          ...(detected?.width ? { width: detected.width } : {}),
          ...(detected?.height ? { height: detected.height } : {}),
        };
        return {
          output: {
            files: [fileEntry],
            attachments,
            model: cfg.model,
            ...(size ? { size } : {}),
            endpoint,
            warnings,
            telemetry: mediaTelemetry(startedAt),
          },
        };
      } catch (error) {
        if (error instanceof ImageGenHttpError) {
          if (endpoint === "edits" && (error.status === 404 || error.status === 405 || error.status === 501)) {
            return toolError(
              "edits_unsupported",
              "the configured image provider does not support reference images (/images/edits); retry generate_image without reference_image_paths",
            );
          }
          return toolError("provider_error", error.message);
        }
        if (error instanceof MediaProviderError) return toolError("provider_error", error.message);
        return toolError("generation_failed", networkErrorMessage(imagesUrl(cfg.endpoint, endpoint), error));
      }
    },
  });
}

interface GeneratedImage {
  data: Buffer;
  mimeType: string;
}

/** HTTP error carrying status + body so edits-unsupported downgrades can match on it. */
class ImageGenHttpError extends Error {
  constructor(
    readonly status: number,
    readonly body: string,
  ) {
    super(`HTTP ${status}: ${body}`);
  }
}

/**
 * POST a JSON text-to-image generation. Faithful to the original: providers
 * that reject `response_format` get one retry without it, and providers that
 * return a URL instead of b64_json get a second download.
 */
async function requestImageGenerate(
  cfg: ResolvedConfig,
  request: { prompt: string; size?: string; signal: AbortSignal },
): Promise<GeneratedImage> {
  const url = imagesUrl(cfg.endpoint, "generations");
  const body = (includeResponseFormat: boolean): string =>
    JSON.stringify({
      model: cfg.model,
      prompt: request.prompt,
      n: 1,
      ...(request.size ? { size: request.size } : {}),
      ...(includeResponseFormat ? { response_format: "b64_json" } : {}),
    });
  return requestImage(
    url,
    (includeResponseFormat) => ({
      headers: { Authorization: `Bearer ${cfg.apiKey}`, "Content-Type": "application/json" },
      body: body(includeResponseFormat),
    }),
    request.signal,
  );
}

/** POST a multipart image-to-image edit with reference image(s). */
async function requestImageEdit(
  cfg: ResolvedConfig,
  request: { prompt: string; size?: string; images: ReferenceImage[]; signal: AbortSignal },
): Promise<GeneratedImage> {
  const url = imagesUrl(cfg.endpoint, "edits");
  const buildForm = (includeResponseFormat: boolean): FormData => {
    const form = new FormData();
    form.set("model", cfg.model);
    form.set("prompt", request.prompt);
    if (request.size) form.set("size", request.size);
    if (includeResponseFormat) form.set("response_format", "b64_json");
    const field = request.images.length > 1 ? "image[]" : "image";
    for (const ref of request.images) {
      form.append(field, new Blob([new Uint8Array(ref.data)], { type: ref.mimeType }), ref.name);
    }
    return form;
  };
  return requestImage(
    url,
    (includeResponseFormat) => ({
      headers: { Authorization: `Bearer ${cfg.apiKey}` },
      body: buildForm(includeResponseFormat),
    }),
    request.signal,
  );
}

/**
 * Shared image POST with two compat fallbacks: a 4xx whose body mentions
 * `response_format` is retried once without it; a payload that returns a `url`
 * instead of `b64_json` is downloaded.
 */
async function requestImage(
  url: string,
  init: (includeResponseFormat: boolean) => { headers: Record<string, string>; body: string | FormData },
  signal: AbortSignal,
): Promise<GeneratedImage> {
  const post = (includeResponseFormat: boolean): Promise<Response> =>
    fetch(url, { method: "POST", ...init(includeResponseFormat), signal });

  let response = await post(true);
  if (!response.ok && response.status >= 400 && response.status < 500) {
    const errorBody = await response.text();
    if (!/response_format/i.test(errorBody)) throw new ImageGenHttpError(response.status, errorBody);
    response = await post(false);
  }
  if (!response.ok) throw new ImageGenHttpError(response.status, await response.text());

  const payload = (await response.json()) as ImagesResponse;
  const entry = payload.data?.[0];
  if (entry?.b64_json) {
    return { data: Buffer.from(entry.b64_json, "base64"), mimeType: "image/png" };
  }
  if (entry?.url) {
    const download = await fetch(entry.url, { signal });
    if (!download.ok) throw new ImageGenHttpError(download.status, await download.text());
    const mimeType = download.headers.get("content-type")?.split(";")[0] || "image/png";
    return { data: Buffer.from(await download.arrayBuffer()), mimeType };
  }
  throw new Error("image provider returned no image data");
}

// --- Async image (protocol: "async-image") ------------------------------

/**
 * Async /v1/image_generation adapter. Faithful to the original
 * AsyncImageClient: a single JSON POST carrying `prompt_optimizer` +
 * `response_format: "base64"`; reference images become a `subject_reference`
 * array of character data-URIs; the response is asserted via `base_resp` and the
 * image bytes come from `data.image_base64[0]` (base64) or a downloaded
 * `data.image_urls[0]`. Dimension fields are derived per-model by
 * {@link asyncImageDimensionFields}.
 */
async function requestAsyncImage(
  cfg: ResolvedConfig,
  request: { prompt: string; size?: string; images?: ReferenceImage[]; signal: AbortSignal },
): Promise<GeneratedImage> {
  const url = asyncImageGenerationUrl(cfg.endpoint);
  const body: Record<string, unknown> = {
    model: cfg.model,
    prompt: request.prompt,
    ...asyncImageDimensionFields(cfg.model, request.size),
    prompt_optimizer: true,
    response_format: "base64",
    n: 1,
  };
  if (request.images && request.images.length > 0) {
    body.subject_reference = request.images.map((image) => ({
      type: "character",
      image_file: `data:${image.mimeType};base64,${image.data.toString("base64")}`,
    }));
  }
  let response: Response;
  try {
    response = await fetch(url, {
      method: "POST",
      headers: { Authorization: `Bearer ${cfg.apiKey}`, "Content-Type": "application/json" },
      body: JSON.stringify(body),
      signal: request.signal,
    });
  } catch (error) {
    throw new Error(networkErrorMessage(url, error));
  }
  const text = await response.text();
  if (!response.ok) throw new ImageGenHttpError(response.status, text);
  let payload: AsyncImageResponse;
  try {
    payload = JSON.parse(text) as AsyncImageResponse;
  } catch {
    throw new Error("Async image provider returned invalid JSON");
  }
  assertAsyncOk(payload.base_resp, "Async image provider");
  const b64 = payload.data?.image_base64?.[0];
  if (b64) {
    return { data: Buffer.from(b64, "base64"), mimeType: "image/jpeg" };
  }
  const imageUrl = payload.data?.image_urls?.[0];
  if (imageUrl) {
    const download = await fetch(imageUrl, { signal: request.signal });
    if (!download.ok) throw new ImageGenHttpError(download.status, await download.text());
    const mimeType = download.headers.get("content-type")?.split(";")[0] || "image/jpeg";
    return { data: Buffer.from(await download.arrayBuffer()), mimeType };
  }
  throw new Error("Async image provider returned no image data");
}

/** Resolve the Async /v1/image_generation URL, tolerating bare/`/v1` bases. */
function asyncImageGenerationUrl(baseUrl: string): string {
  const normalized = trimTrailingSlashes(baseUrl.trim());
  const lower = normalized.toLowerCase();
  if (!normalized) return "/v1/image_generation";
  if (lower.endsWith("/v1/image_generation") || lower.endsWith("/image_generation")) return normalized;
  if (lower.endsWith("/v1")) return `${normalized}/image_generation`;
  return `${normalized}/v1/image_generation`;
}

/** Async aspect-ratio table used to snap a WxH onto the nearest label. */
const ASYNC_ASPECT_RATIOS: Array<{ label: string; value: number }> = [
  { label: "1:1", value: 1 },
  { label: "16:9", value: 16 / 9 },
  { label: "4:3", value: 4 / 3 },
  { label: "3:2", value: 3 / 2 },
  { label: "2:3", value: 2 / 3 },
  { label: "3:4", value: 3 / 4 },
  { label: "9:16", value: 9 / 16 },
];

/**
 * Derive Async dimension fields from a `WxH` size string. `image-01` accepts
 * explicit `{ width, height }`; other models accept the nearest
 * `{ aspect_ratio }` label (log-distance match). Faithful port.
 */
function asyncImageDimensionFields(model: string, size: string | undefined): Record<string, unknown> {
  const match = size?.trim().match(/^(\d+)x(\d+)$/);
  if (!match) return {};
  const width = Number(match[1]);
  const height = Number(match[2]);
  if (!Number.isFinite(width) || !Number.isFinite(height) || width <= 0 || height <= 0) return {};
  if (model.trim() === "image-01") return { width, height };
  const target = width / height;
  let best = ASYNC_ASPECT_RATIOS[0];
  let bestDiff = Number.POSITIVE_INFINITY;
  for (const candidate of ASYNC_ASPECT_RATIOS) {
    const diff = Math.abs(Math.log(candidate.value / target));
    if (diff < bestDiff) {
      bestDiff = diff;
      best = candidate;
    }
  }
  return { aspect_ratio: best.label };
}

// --- generate_speech --------------------------------------------------------

function buildSpeechTool(speech: MediaEndpointConfig | undefined, outputDir: string): LocalTool {
  return defineTool({
    name: "generate_speech",
    description: [
      "Generate spoken audio from text using the configured text-to-speech provider.",
      "The generated audio is written to a hidden media directory and returned as a generated file.",
      "Use voice for a provider voice id/name and style for voice-style instructions when needed.",
    ].join(" "),
    toolKind: "tool_call",
    policy: "untrusted",
    inputSchema: {
      type: "object",
      properties: {
        text: { type: "string", description: "Text to synthesize into speech" },
        voice: { type: "string", description: "Optional provider voice id/name" },
        style: { type: "string", description: "Optional voice style instruction for providers that support it" },
        format: { type: "string", enum: [...AUDIO_FORMATS] },
      },
      required: ["text"],
      additionalProperties: false,
    },
    async execute(args, context) {
      const startedAt = Date.now();
      const cfg = resolveConfig(speech);
      if (!cfg) return notConfigured("speech");
      const text = pickString(args.text);
      if (!text) return toolError("invalid_text", "text is required");
      // Format falls back to the configured default, then mp3.
      const format = normalizeAudioFormat(pickString(args.format) ?? pickString(speech?.format));
      // Vendor protocols accept an optional voice; OpenAI-compat falls back to
      // "alloy" only when none is supplied (faithful to OpenAiCompatSpeechClient).
      // A configured default voice is used when the tool-call omits one.
      const voiceArg = pickString(args.voice) ?? pickString(speech?.voice);
      const style = pickString(args.style);
      const signal = withTimeout(context.abortSignal, resolveTimeoutMs(speech));
      try {
        const media =
          cfg.protocol === "async-t2a"
            ? await requestAsyncSpeech(cfg, { text, voice: voiceArg, format, signal })
            : cfg.protocol === "mimo-tts"
              ? await requestMimoSpeech(cfg, { text, voice: voiceArg, style, format, signal })
              : await requestOpenAiSpeech(cfg, { text, voice: voiceArg, style, format, signal });
        const file = await writeMediaFile(outputDir, "speech", audioExtension(format), media.data, media.mimeType);
        return {
          output: {
            files: [file],
            model: cfg.model,
            ...(voiceArg ? { voice: voiceArg } : {}),
            format,
            telemetry: mediaTelemetry(startedAt),
          },
        };
      } catch (error) {
        if (error instanceof MediaProviderError) return toolError("provider_error", error.message);
        return toolError("generation_failed", networkErrorMessage(apiUrl(cfg.endpoint, "/v1/audio/speech"), error));
      }
    },
  });
}

interface SpeechRequest {
  text: string;
  voice?: string;
  style?: string;
  format: string;
  signal: AbortSignal;
}

/** OpenAI-compatible /v1/audio/speech (default speech path). */
async function requestOpenAiSpeech(cfg: ResolvedConfig, request: SpeechRequest): Promise<DecodedAudio> {
  const url = apiUrl(cfg.endpoint, "/v1/audio/speech");
  const response = await fetch(url, {
    method: "POST",
    headers: { Authorization: `Bearer ${cfg.apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      model: cfg.model,
      input: request.text,
      voice: request.voice || "alloy",
      ...(request.style ? { style: request.style } : {}),
      response_format: request.format,
    }),
    signal: request.signal,
  });
  if (!response.ok) throw new MediaProviderError(`HTTP ${response.status}: ${await response.text()}`);
  const mimeType = response.headers.get("content-type")?.split(";")[0] || audioMimeType(request.format);
  return { data: Buffer.from(await response.arrayBuffer()), mimeType };
}

/**
 * Async /v1/t2a_v2 text-to-audio. Faithful to AsyncSpeechClient: requests
 * `output_format: "hex"`, sends voice_setting/audio_setting blocks, asserts
 * `base_resp`, and decodes `data.audio` as hex via {@link bufferFromHex}.
 */
async function requestAsyncSpeech(cfg: ResolvedConfig, request: SpeechRequest): Promise<DecodedAudio> {
  const url = apiUrl(cfg.endpoint, "/v1/t2a_v2");
  const voiceId = request.voice || "male-qn-qingse";
  const payload = await requestJson<AsyncAudioResponse>(url, {
    method: "POST",
    headers: { Authorization: `Bearer ${cfg.apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      model: cfg.model,
      text: request.text,
      output_format: "hex",
      voice_setting: { voice_id: voiceId, speed: 1, vol: 1, pitch: 0 },
      audio_setting: {
        format: request.format,
        sample_rate: request.format === "mp3" ? 32_000 : 44_100,
        bitrate: 128_000,
        channel: 1,
      },
    }),
    signal: request.signal,
  });
  assertAsyncOk(payload.base_resp, "Async speech provider");
  const audio = payload.data?.audio;
  if (!audio) throw new Error("Async speech provider returned no audio data");
  return { data: bufferFromHex(audio), mimeType: audioMimeType(request.format) };
}

/**
 * Xiaomi MiMo /v1/chat/completions TTS. Faithful to MimoSpeechClient: the style
 * (when present) becomes a leading user message, the text an assistant message,
 * an `audio` block carries the format + optional voice, both `Authorization` and
 * `api-key` headers are set, and the audio is base64 in
 * `choices[0].message.audio.data`.
 */
async function requestMimoSpeech(cfg: ResolvedConfig, request: SpeechRequest): Promise<DecodedAudio> {
  const url = apiUrl(cfg.endpoint, "/v1/chat/completions");
  const messages = [
    ...(request.style ? [{ role: "user", content: request.style }] : []),
    { role: "assistant", content: request.text },
  ];
  const payload = await requestJson<MimoSpeechResponse>(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${cfg.apiKey}`,
      "api-key": cfg.apiKey,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: cfg.model,
      messages,
      audio: { format: request.format, ...(request.voice ? { voice: request.voice } : {}) },
    }),
    signal: request.signal,
  });
  const audio = payload.choices?.[0]?.message?.audio?.data;
  if (!audio) throw new Error("MiMo speech provider returned no audio data");
  return { data: Buffer.from(audio, "base64"), mimeType: audioMimeType(request.format) };
}

// --- generate_music ---------------------------------------------------------

function buildMusicTool(music: MediaEndpointConfig | undefined, outputDir: string): LocalTool {
  return defineTool({
    name: "generate_music",
    description: [
      "Generate a song or instrumental audio using the configured music provider.",
      "The generated audio is written to a hidden media directory and returned as a generated file.",
      "Provide prompt for style/intention, lyrics for sung music, or instrumental=true for instrumental tracks.",
    ].join(" "),
    toolKind: "tool_call",
    policy: "untrusted",
    inputSchema: {
      type: "object",
      properties: {
        prompt: { type: "string", description: "Musical style, mood, arrangement, or generation prompt" },
        lyrics: { type: "string", description: "Optional lyrics for sung music" },
        instrumental: { type: "boolean", description: "Generate instrumental music without vocals" },
        lyrics_optimizer: { type: "boolean", description: "Ask provider to generate or improve lyrics" },
        reference_audio_url: { type: "string", description: "Optional public URL for cover/reference audio" },
        format: { type: "string", enum: [...AUDIO_FORMATS] },
      },
      additionalProperties: false,
    },
    async execute(args, context) {
      const startedAt = Date.now();
      const cfg = resolveConfig(music);
      if (!cfg) return notConfigured("music");
      const prompt = pickString(args.prompt);
      const lyrics = pickString(args.lyrics);
      const instrumental = pickBoolean(args.instrumental);
      const lyricsOptimizer = pickBoolean(args.lyrics_optimizer);
      const referenceAudioUrl = pickString(args.reference_audio_url);
      if (!prompt && !lyrics && instrumental !== true) {
        return toolError("invalid_music_request", "provide prompt, lyrics, or instrumental=true");
      }
      const format = normalizeAudioFormat(pickString(args.format) ?? pickString(music?.format));
      const signal = withTimeout(context.abortSignal, resolveTimeoutMs(music));
      if (cfg.protocol === "async-music") {
        try {
          const media = await requestAsyncMusic(cfg, {
            prompt,
            lyrics,
            instrumental,
            lyricsOptimizer,
            referenceAudioUrl,
            format,
            signal,
          });
          const file = await writeMediaFile(outputDir, "music", audioExtension(format), media.data, media.mimeType);
          return { output: { files: [file], model: cfg.model, format, telemetry: mediaTelemetry(startedAt) } };
        } catch (error) {
          if (error instanceof MediaProviderError) return toolError("provider_error", error.message);
          return toolError("generation_failed", networkErrorMessage(asyncMusicUrl(cfg.endpoint), error));
        }
      }
      const url = apiUrl(cfg.endpoint, "/v1/music/generations");
      try {
        const response = await fetch(url, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${cfg.apiKey}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            model: cfg.model,
            ...(prompt ? { prompt } : {}),
            ...(lyrics ? { lyrics } : {}),
            ...(instrumental !== undefined ? { instrumental } : {}),
            ...(lyricsOptimizer !== undefined ? { lyrics_optimizer: lyricsOptimizer } : {}),
            ...(referenceAudioUrl ? { reference_audio_url: referenceAudioUrl } : {}),
            response_format: "b64_json",
            format,
          }),
          signal,
        });
        if (!response.ok) {
          return toolError("provider_error", `HTTP ${response.status}: ${await response.text()}`);
        }
        const media = await decodeAudioPayload(response, format, signal);
        if ("error" in media) return media.error;
        const file = await writeMediaFile(outputDir, "music", format, media.data, media.mimeType);
        return { output: { files: [file], model: cfg.model, format, telemetry: mediaTelemetry(startedAt) } };
      } catch (error) {
        return toolError("generation_failed", networkErrorMessage(url, error));
      }
    },
  });
}

interface MusicRequest {
  prompt?: string;
  lyrics?: string;
  instrumental?: boolean;
  lyricsOptimizer?: boolean;
  referenceAudioUrl?: string;
  format: string;
  signal: AbortSignal;
}

/** Resolve the Async /v1/music_generation URL, tolerating bare/`/v1` bases. */
function asyncMusicUrl(baseUrl: string): string {
  return apiUrl(baseUrl, "/v1/music_generation");
}

/**
 * Async /v1/music_generation. Faithful to AsyncMusicClient: requests
 * `output_format: "hex"`, sends an audio_setting block, defaults
 * `lyrics_optimizer` to true only when no lyrics and not instrumental, maps
 * instrumental to `is_instrumental` and the reference URL to `audio_url`,
 * asserts `base_resp`, and decodes `data.audio` as hex.
 */
async function requestAsyncMusic(cfg: ResolvedConfig, request: MusicRequest): Promise<DecodedAudio> {
  const url = asyncMusicUrl(cfg.endpoint);
  const payload = await requestJson<AsyncAudioResponse>(url, {
    method: "POST",
    headers: { Authorization: `Bearer ${cfg.apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      model: cfg.model,
      ...(request.prompt ? { prompt: request.prompt } : {}),
      ...(request.lyrics ? { lyrics: request.lyrics } : {}),
      output_format: "hex",
      audio_setting: { format: request.format, sample_rate: 44_100, bitrate: 256_000 },
      lyrics_optimizer: request.lyricsOptimizer ?? (!request.lyrics && request.instrumental !== true),
      ...(request.instrumental !== undefined ? { is_instrumental: request.instrumental } : {}),
      ...(request.referenceAudioUrl ? { audio_url: request.referenceAudioUrl } : {}),
    }),
    signal: request.signal,
  });
  assertAsyncOk(payload.base_resp, "Async music provider");
  const audio = payload.data?.audio;
  if (!audio) throw new Error("Async music provider returned no audio data");
  return { data: bufferFromHex(audio), mimeType: audioMimeType(request.format) };
}

// --- generate_video ---------------------------------------------------------

function buildVideoTool(video: MediaEndpointConfig | undefined, outputDir: string): LocalTool {
  return defineTool({
    name: "generate_video",
    description: [
      "Generate a video from a text prompt using the configured video endpoint.",
      "Optionally pass workspace-relative first_frame_image_path and last_frame_image_path for image-to-video guidance.",
      "Submission is asynchronous: the task is submitted then polled until it completes.",
      "The generated video is written to a hidden media directory and its absolute path is returned.",
    ].join(" "),
    toolKind: "tool_call",
    policy: "untrusted",
    inputSchema: {
      type: "object",
      properties: {
        prompt: { type: "string", description: "Detailed video generation prompt" },
        duration: { type: "integer", minimum: 1, maximum: 30 },
        resolution: { type: "string", enum: VIDEO_RESOLUTIONS },
        first_frame_image_path: { type: "string", description: "Workspace-relative png/jpeg/webp first frame" },
        last_frame_image_path: { type: "string", description: "Workspace-relative png/jpeg/webp last frame" },
      },
      required: ["prompt"],
      additionalProperties: false,
    },
    async execute(args, context, onUpdate) {
      const startedAt = Date.now();
      const cfg = resolveConfig(video);
      if (!cfg) return notConfigured("video");
      const prompt = pickString(args.prompt);
      if (!prompt) return toolError("invalid_prompt", "prompt is required");
      const firstFrame = await collectFrameImage(args.first_frame_image_path, context.workspace, "first_frame_image_path");
      if ("error" in firstFrame) return firstFrame.error;
      const lastFrame = await collectFrameImage(args.last_frame_image_path, context.workspace, "last_frame_image_path");
      if ("error" in lastFrame) return lastFrame.error;
      // Duration/resolution fall back to the configured per-modality defaults
      // when the tool-call omits them.
      const duration = normalizeDuration(args.duration ?? video?.defaultDuration);
      const resolution = pickString(args.resolution) ?? pickString(video?.defaultResolution);
      const timeoutMs = resolveTimeoutMs(video);
      const signal = withTimeout(context.abortSignal, timeoutMs);
      if (cfg.protocol === "async-video") {
        try {
          const media = await requestAsyncVideo(cfg, {
            prompt,
            duration,
            resolution,
            ...(firstFrame.image ? { firstFrameImage: firstFrame.image } : {}),
            ...(lastFrame.image ? { lastFrameImage: lastFrame.image } : {}),
            signal,
            timeoutMs,
            onUpdate,
          });
          const file = await writeMediaFile(outputDir, "video", videoExtension(media.mimeType), media.data, media.mimeType);
          return {
            output: {
              files: [file],
              model: cfg.model,
              ...(duration !== undefined ? { duration } : {}),
              ...(resolution ? { resolution } : {}),
              telemetry: mediaTelemetry(startedAt),
            },
          };
        } catch (error) {
          if (error instanceof MediaProviderError) return toolError("provider_error", error.message);
          return toolError("generation_failed", networkErrorMessage(asyncRootUrl(cfg.endpoint), error));
        }
      }
      const createUrl = apiUrl(cfg.endpoint, "/v1/video/generations");
      try {
        const createResponse = await fetch(createUrl, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${cfg.apiKey}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            model: cfg.model,
            prompt,
            ...(duration !== undefined ? { duration } : {}),
            ...(resolution ? { resolution } : {}),
            ...(firstFrame.image ? { first_frame_image: dataUri(firstFrame.image.mimeType, firstFrame.image.data) } : {}),
            ...(lastFrame.image ? { last_frame_image: dataUri(lastFrame.image.mimeType, lastFrame.image.data) } : {}),
          }),
          signal,
        });
        if (!createResponse.ok) {
          return toolError("provider_error", `HTTP ${createResponse.status}: ${await createResponse.text()}`);
        }
        const created = (await createResponse.json()) as VideoSubmitResponse;
        const taskId = created.task_id || created.id;
        if (!taskId) {
          // Some endpoints return the asset synchronously.
          const direct = await resolveVideoAsset(created, cfg, signal);
          if (direct) {
            const file = await writeMediaFile(outputDir, "video", videoExtension(direct.mimeType), direct.data, direct.mimeType);
            return {
              output: {
                files: [file],
                model: cfg.model,
                ...(duration !== undefined ? { duration } : {}),
                telemetry: mediaTelemetry(startedAt),
              },
            };
          }
          return toolError("generation_failed", "video provider returned no task_id or asset");
        }
        await emit(onUpdate, { status: "submitted", taskId });
        const queryUrl = apiUrl(cfg.endpoint, "/v1/video/generations");
        const deadline = Date.now() + timeoutMs;
        let lastStatus = "submitted";
        while (Date.now() < deadline) {
          await delay(DEFAULT_POLL_INTERVAL_MS, signal);
          const query = new URL(`${queryUrl}/${encodeURIComponent(taskId)}`);
          const queryResponse = await fetch(query.toString(), {
            method: "GET",
            headers: { Authorization: `Bearer ${cfg.apiKey}` },
            signal,
          });
          if (!queryResponse.ok) {
            return toolError("provider_error", `HTTP ${queryResponse.status}: ${await queryResponse.text()}`);
          }
          const queryPayload = (await queryResponse.json()) as VideoSubmitResponse;
          lastStatus = queryPayload.status || lastStatus;
          await emit(onUpdate, { status: lastStatus, taskId });
          if (isFailureStatus(lastStatus)) {
            return toolError("generation_failed", `video generation failed with status ${lastStatus}`);
          }
          if (!isSuccessStatus(lastStatus)) continue;
          const asset = await resolveVideoAsset(queryPayload, cfg, signal);
          if (!asset) return toolError("generation_failed", "video provider finished without an asset");
          const file = await writeMediaFile(outputDir, "video", videoExtension(asset.mimeType), asset.data, asset.mimeType);
          return {
            output: {
              files: [file],
              model: cfg.model,
              ...(duration !== undefined ? { duration } : {}),
              ...(resolution ? { resolution } : {}),
              telemetry: mediaTelemetry(startedAt),
            },
          };
        }
        return toolError("generation_failed", `video generation timed out after ${timeoutMs}ms (last status: ${lastStatus})`);
      } catch (error) {
        return toolError("generation_failed", networkErrorMessage(createUrl, error));
      }
    },
  });
}

interface AsyncVideoRequest {
  prompt: string;
  duration?: number;
  resolution?: string;
  firstFrameImage?: ReferenceImage;
  lastFrameImage?: ReferenceImage;
  signal: AbortSignal;
  /** Poll deadline budget in ms; falls back to DEFAULT_TIMEOUT_MS when absent. */
  timeoutMs?: number;
  onUpdate?: ToolUpdate;
}

/**
 * Async media video pipeline (protocol: "async-video"). Faithful to
 * AsyncVideoClient: POST /v1/video_generation (first/last frame as data-URIs)
 * to obtain a `task_id`; emit a "submitted" onUpdate; then poll
 * /v1/query/video_generation?task_id= on a deadline, emitting each status; on
 * success read `file_id`, resolve its `download_url` via
 * /v1/files/retrieve?file_id=, and download the bytes. base_resp is asserted on
 * every JSON response.
 */
async function requestAsyncVideo(cfg: ResolvedConfig, request: AsyncVideoRequest): Promise<DecodedAudio> {
  const root = asyncRootUrl(cfg.endpoint);
  const headers = (): Record<string, string> => ({
    Authorization: `Bearer ${cfg.apiKey}`,
    "Content-Type": "application/json",
  });
  const createPayload = await requestJson<AsyncVideoResponse>(`${root}/v1/video_generation`, {
    method: "POST",
    headers: headers(),
    body: JSON.stringify({
      model: cfg.model,
      prompt: request.prompt,
      ...(request.duration !== undefined ? { duration: request.duration } : {}),
      ...(request.resolution ? { resolution: request.resolution } : {}),
      ...(request.firstFrameImage
        ? { first_frame_image: dataUri(request.firstFrameImage.mimeType, request.firstFrameImage.data) }
        : {}),
      ...(request.lastFrameImage
        ? { last_frame_image: dataUri(request.lastFrameImage.mimeType, request.lastFrameImage.data) }
        : {}),
    }),
    signal: request.signal,
  });
  assertAsyncOk(createPayload.base_resp, "Async video provider");
  const taskId = createPayload.task_id;
  if (!taskId) throw new Error("Async video provider returned no task_id");
  await emit(request.onUpdate, { status: "submitted", taskId, provider: "async-video" });

  const deadline = Date.now() + (request.timeoutMs ?? DEFAULT_TIMEOUT_MS);
  let lastStatus = "submitted";
  while (Date.now() < deadline) {
    await delay(DEFAULT_POLL_INTERVAL_MS, request.signal);
    const queryUrl = new URL(`${root}/v1/query/video_generation`);
    queryUrl.searchParams.set("task_id", taskId);
    const queryPayload = await requestJson<AsyncVideoResponse>(queryUrl.toString(), {
      method: "GET",
      headers: headers(),
      signal: request.signal,
    });
    assertAsyncOk(queryPayload.base_resp, "Async video provider");
    lastStatus = queryPayload.status || lastStatus;
    await emit(request.onUpdate, { status: lastStatus, taskId, provider: "async-video" });
    if (isFailureStatus(lastStatus)) {
      throw new Error(`Async video generation failed with status ${lastStatus}`);
    }
    if (!isSuccessStatus(lastStatus)) continue;
    const fileId = queryPayload.file_id;
    if (!fileId) throw new Error("Async video provider finished without file_id");
    const downloadUrl = await retrieveAsyncDownloadUrl(root, fileId, cfg, request.signal);
    const response = await fetch(downloadUrl, { method: "GET", signal: request.signal });
    if (!response.ok) throw new ImageGenHttpError(response.status, await response.text());
    const mimeType = response.headers.get("content-type")?.split(";")[0] || "video/mp4";
    return { data: Buffer.from(await response.arrayBuffer()), mimeType };
  }
  throw new Error(`Async video generation timed out after ${request.timeoutMs ?? DEFAULT_TIMEOUT_MS}ms (last status: ${lastStatus})`);
}

/** Resolve a Async file_id to its signed download_url via /v1/files/retrieve. */
async function retrieveAsyncDownloadUrl(
  root: string,
  fileId: string,
  cfg: ResolvedConfig,
  signal: AbortSignal,
): Promise<string> {
  const retrieveUrl = new URL(`${root}/v1/files/retrieve`);
  retrieveUrl.searchParams.set("file_id", fileId);
  const payload = await requestJson<AsyncVideoResponse>(retrieveUrl.toString(), {
    method: "GET",
    headers: { Authorization: `Bearer ${cfg.apiKey}`, "Content-Type": "application/json" },
    signal,
  });
  assertAsyncOk(payload.base_resp, "Async video provider");
  const downloadUrl = payload.file?.download_url;
  if (!downloadUrl) throw new Error("Async video provider returned no download_url");
  return downloadUrl;
}

/**
 * Strip a Async video route suffix (or trailing `/v1`) off a configured base so
 * the absolute /v1/video_generation, /v1/query/video_generation and
 * /v1/files/retrieve URLs can be composed from a common root. Faithful port.
 */
function asyncRootUrl(baseUrl: string): string {
  const normalized = trimTrailingSlashes(baseUrl.trim());
  if (!normalized) return "";
  for (const suffix of ["/v1/video_generation", "/video_generation", "/v1/query/video_generation"]) {
    if (normalized.toLowerCase().endsWith(suffix)) {
      return trimTrailingSlashes(normalized.slice(0, -suffix.length));
    }
  }
  if (normalized.toLowerCase().endsWith("/v1")) return trimTrailingSlashes(normalized.slice(0, -3));
  return normalized;
}

// --- shared helpers ---------------------------------------------------------

interface ResolvedConfig {
  endpoint: string;
  apiKey: string;
  model: string;
  /** Vendor wire-shape selector; empty/omitted/unknown => OpenAI-compatible. */
  protocol?: string;
}

function resolveConfig(cfg: MediaEndpointConfig | undefined): ResolvedConfig | null {
  if (!cfg) return null;
  const endpoint = pickString(cfg.endpoint);
  const apiKey = pickString(cfg.apiKey);
  const model = pickString(cfg.model);
  if (!endpoint || !apiKey || !model) return null;
  const protocol = pickString(cfg.protocol)?.toLowerCase();
  return { endpoint, apiKey, model, ...(protocol ? { protocol } : {}) };
}

function notConfigured(modality: string): ToolResult {
  return toolError(
    "not_configured",
    `${modality} generation is not configured; set an endpoint, apiKey, and model for the ${modality} media provider`,
  );
}

interface MediaFileResult {
  relativePath: string;
  absolutePath: string;
  mimeType: string;
  byteSize: number;
}

async function writeMediaFile(
  outputDir: string,
  prefix: string,
  extension: string,
  data: Buffer,
  mimeType: string,
): Promise<MediaFileResult> {
  const stamp = new Date().toISOString().replace(/\D/g, "").slice(0, 14);
  const fileName = `${prefix}-${stamp}-${randomBytes(2).toString("hex")}.${extension}`;
  const relativePath = `${MEDIA_DIR}/${fileName}`;
  const dir = join(outputDir, MEDIA_DIR);
  const absolutePath = join(dir, fileName);
  await mkdir(dir, { recursive: true });
  await writeFile(absolutePath, data);
  return { relativePath, absolutePath, mimeType, byteSize: data.byteLength };
}

/** Telemetry block attached to every media output: { provider, durationMs }. */
function mediaTelemetry(startedAt: number): { provider: string; durationMs: number } {
  return { provider: "media", durationMs: Date.now() - startedAt };
}

/**
 * Resolve a per-modality request timeout: the configured `timeoutMs` when it is
 * a positive finite number, otherwise the shared {@link DEFAULT_TIMEOUT_MS}.
 */
function resolveTimeoutMs(cfg: MediaEndpointConfig | undefined): number {
  const value = cfg?.timeoutMs;
  return typeof value === "number" && Number.isFinite(value) && value > 0 ? value : DEFAULT_TIMEOUT_MS;
}

/** Coerce an audio format arg to a supported AUDIO_FORMATS value (default mp3). */
function normalizeAudioFormat(format: string | undefined): string {
  const normalized = (format ?? "").toLowerCase();
  return (AUDIO_FORMATS as readonly string[]).includes(normalized) ? normalized : "mp3";
}

interface DecodedAudio {
  data: Buffer;
  mimeType: string;
}

async function decodeAudioPayload(
  response: Response,
  format: string,
  signal: AbortSignal,
): Promise<DecodedAudio | { error: ToolResult }> {
  const contentType = response.headers.get("content-type")?.split(";")[0] || "";
  if (contentType.startsWith("audio/") || contentType === "application/octet-stream") {
    return { data: Buffer.from(await response.arrayBuffer()), mimeType: contentType || audioMimeType(format) };
  }
  let payload: AudioResponse;
  try {
    payload = (await response.json()) as AudioResponse;
  } catch {
    return { error: toolError("generation_failed", "music provider returned invalid response") };
  }
  const entry = payload.data?.[0] ?? payload;
  if (entry?.b64_json) {
    return { data: Buffer.from(entry.b64_json, "base64"), mimeType: audioMimeType(format) };
  }
  if (entry?.audio) {
    return { data: Buffer.from(entry.audio, "base64"), mimeType: audioMimeType(format) };
  }
  if (entry?.url) {
    const download = await fetch(entry.url, { signal });
    if (!download.ok) {
      return { error: toolError("provider_error", `HTTP ${download.status}: ${await download.text()}`) };
    }
    const mimeType = download.headers.get("content-type")?.split(";")[0] || audioMimeType(format);
    return { data: Buffer.from(await download.arrayBuffer()), mimeType };
  }
  return { error: toolError("generation_failed", "music provider returned no audio data") };
}

async function resolveVideoAsset(
  payload: VideoSubmitResponse,
  cfg: ResolvedConfig,
  signal: AbortSignal,
): Promise<DecodedAudio | null> {
  const url = payload.video_url || payload.url || payload.data?.[0]?.url;
  if (url) {
    const download = await fetch(url, {
      signal,
      headers: { Authorization: `Bearer ${cfg.apiKey}` },
    });
    if (!download.ok) return null;
    const mimeType = download.headers.get("content-type")?.split(";")[0] || "video/mp4";
    return { data: Buffer.from(await download.arrayBuffer()), mimeType };
  }
  const b64 = payload.b64_json || payload.data?.[0]?.b64_json;
  if (b64) return { data: Buffer.from(b64, "base64"), mimeType: "video/mp4" };
  return null;
}

function imagesUrl(endpoint: string, kind: "generations" | "edits" = "generations"): string {
  const lower = endpoint.toLowerCase();
  // If the configured endpoint already names a specific images route, switch
  // only its trailing segment so edits/generations stay consistent.
  if (lower.endsWith("/images/generations") || lower.endsWith("/images/edits")) {
    return endpoint.replace(/\/images\/(generations|edits)$/i, `/images/${kind}`);
  }
  if (lower.includes("/images/")) return endpoint;
  return apiUrl(endpoint, `/v1/images/${kind}`);
}

function apiUrl(baseUrl: string, v1Path: string): string {
  const normalized = trimTrailingSlashes(baseUrl.trim());
  const lower = normalized.toLowerCase();
  const path = v1Path.startsWith("/") ? v1Path : `/${v1Path}`;
  const pathWithoutV1 = path.startsWith("/v1/") ? path.slice("/v1".length) : path;
  if (!normalized) return path;
  if (lower.endsWith(path.toLowerCase()) || lower.endsWith(pathWithoutV1.toLowerCase())) return normalized;
  if (lower.endsWith("/v1")) return `${normalized}${pathWithoutV1}`;
  return `${normalized}${path}`;
}

function trimTrailingSlashes(value: string): string {
  let end = value.length;
  while (end > 0 && value.charCodeAt(end - 1) === 47) end -= 1;
  return end === value.length ? value : value.slice(0, end);
}

function withTimeout(signal: AbortSignal, timeoutMs: number): AbortSignal {
  return AbortSignal.any([signal, AbortSignal.timeout(timeoutMs)]);
}

function delay(ms: number, signal: AbortSignal): Promise<void> {
  if (signal.aborted) return Promise.reject(new DOMException("Aborted", "AbortError"));
  return new Promise((resolveDelay, rejectDelay) => {
    const timer = setTimeout(resolveDelay, ms);
    const abort = () => {
      clearTimeout(timer);
      rejectDelay(new DOMException("Aborted", "AbortError"));
    };
    signal.addEventListener("abort", abort, { once: true });
  });
}

async function emit(onUpdate: ToolUpdate | undefined, output: Record<string, unknown>): Promise<void> {
  onUpdate?.({ output });
}

function imageExtension(mimeType: string): string {
  if (mimeType === "image/jpeg") return "jpg";
  if (mimeType === "image/webp") return "webp";
  if (mimeType === "image/gif") return "gif";
  return "png";
}

// --- reference images + size mapping (ported from image-gen) -----------------

interface ReferenceImage {
  name: string;
  mimeType: string;
  data: Buffer;
}

interface DetectedImageInfo {
  mimeType: string;
  width?: number;
  height?: number;
}

/**
 * Magic-byte image sniffing returning {mimeType, width?, height?}. PNG yields
 * dimensions from the IHDR chunk; JPEG/WEBP are recognized by signature only.
 */
function detectImageDimensions(buffer: Buffer): DetectedImageInfo | null {
  if (
    buffer.length >= 24 &&
    buffer[0] === 0x89 &&
    buffer[1] === 0x50 &&
    buffer[2] === 0x4e &&
    buffer[3] === 0x47
  ) {
    return { mimeType: "image/png", width: buffer.readUInt32BE(16), height: buffer.readUInt32BE(20) };
  }
  if (buffer.length >= 3 && buffer[0] === 0xff && buffer[1] === 0xd8 && buffer[2] === 0xff) {
    return { mimeType: "image/jpeg" };
  }
  if (
    buffer.length >= 12 &&
    buffer.subarray(0, 4).toString("ascii") === "RIFF" &&
    buffer.subarray(8, 12).toString("ascii") === "WEBP"
  ) {
    return { mimeType: "image/webp" };
  }
  const mime = detectImageMime(buffer);
  return mime ? { mimeType: mime.mimeType } : null;
}

/**
 * Map an aspect_ratio + image_size tier to a `WxH` size string. Returns the
 * `defaultSize` when neither is supplied. Square ratios use the tier on both
 * edges; otherwise the short edge is `round(tier * short/long / 64) * 64`,
 * clamped to a 256px minimum. Faithful port of the original `mapImageSize`.
 */
function mapImageSize(
  aspectRatio: string | undefined,
  imageSize: string | undefined,
  defaultSize: string | undefined,
): string | undefined {
  if (!aspectRatio && !imageSize) return defaultSize;
  const tier = SIZE_TIERS[imageSize ?? ""] ?? SIZE_TIERS["1K"];
  const parsed = parseRatio(aspectRatio);
  if (!parsed) return `${tier}x${tier}`;
  const { w, h } = parsed;
  if (w === h) return `${tier}x${tier}`;
  const short = Math.max(MIN_EDGE, Math.round(((tier * Math.min(w, h)) / Math.max(w, h)) / SIZE_STEP) * SIZE_STEP);
  return w > h ? `${tier}x${short}` : `${short}x${tier}`;
}

function parseRatio(aspectRatio: string | undefined): { w: number; h: number } | null {
  if (!aspectRatio || !ASPECT_RATIOS.has(aspectRatio)) return null;
  const [w, h] = aspectRatio.split(":").map(Number);
  if (!Number.isFinite(w) || !Number.isFinite(h) || w <= 0 || h <= 0) return null;
  return { w, h };
}

type ReferenceCollection = { images: ReferenceImage[] } | { error: ToolResult };

/**
 * Validate + load workspace-sandboxed reference images for image-to-image.
 * Rejects non-array input, over-count, escapes the workspace, missing files,
 * oversized files, and non-png/jpeg/webp content. Faithful port.
 */
async function collectReferenceImages(
  value: unknown,
  workspace: string,
  maxCount: number,
): Promise<ReferenceCollection> {
  if (value === undefined || value === null) return { images: [] };
  if (!Array.isArray(value)) {
    return { error: toolError("invalid_reference_path", "reference_image_paths must be an array of strings") };
  }
  const paths = value.filter((entry): entry is string => typeof entry === "string" && entry.trim().length > 0);
  if (paths.length > maxCount) {
    return { error: toolError("invalid_reference_path", `at most ${maxCount} reference images are allowed`) };
  }
  const images: ReferenceImage[] = [];
  for (const rawPath of paths) {
    const resolved = resolve(workspace, rawPath);
    const rel = relative(workspace, resolved);
    if (rel.startsWith("..") || isAbsolute(rel)) {
      return { error: toolError("invalid_reference_path", `reference image must be inside the workspace: ${rawPath}`) };
    }
    let data: Buffer;
    try {
      data = await readFile(resolved);
    } catch {
      return { error: toolError("invalid_reference_path", `reference image not found: ${rawPath}`) };
    }
    if (data.byteLength > MAX_REFERENCE_IMAGE_BYTES) {
      return {
        error: toolError("invalid_reference_path", `reference image exceeds ${MAX_REFERENCE_IMAGE_BYTES} byte limit: ${rawPath}`),
      };
    }
    const detected = detectImageDimensions(data);
    if (!detected || !REFERENCE_MIME_TYPES.has(detected.mimeType)) {
      return { error: toolError("invalid_reference_path", `reference image must be png, jpeg, or webp: ${rawPath}`) };
    }
    images.push({ name: rawPath.split("/").pop() || "reference.png", mimeType: detected.mimeType, data });
  }
  return { images };
}

type FrameCollection = { image?: ReferenceImage } | { error: ToolResult };

/**
 * Validate + load a single workspace-sandboxed frame image for image-to-video.
 * Returns {} when no path supplied. Faithful port of the original
 * collectFrameImage.
 */
async function collectFrameImage(
  value: unknown,
  workspace: string,
  fieldName: string,
): Promise<FrameCollection> {
  const rawPath = pickString(value);
  if (!rawPath) return {};
  const resolved = resolve(workspace, rawPath);
  const rel = relative(workspace, resolved);
  if (rel.startsWith("..") || isAbsolute(rel)) {
    return { error: toolError("invalid_reference_path", `${fieldName} must be inside the workspace: ${rawPath}`) };
  }
  let data: Buffer;
  try {
    data = await readFile(resolved);
  } catch {
    return { error: toolError("invalid_reference_path", `${fieldName} not found: ${rawPath}`) };
  }
  if (data.byteLength > MAX_REFERENCE_IMAGE_BYTES) {
    return { error: toolError("invalid_reference_path", `${fieldName} exceeds ${MAX_REFERENCE_IMAGE_BYTES} byte limit: ${rawPath}`) };
  }
  const detected = detectImageDimensions(data);
  if (!detected || !REFERENCE_MIME_TYPES.has(detected.mimeType)) {
    return { error: toolError("invalid_reference_path", `${fieldName} must be png, jpeg, or webp: ${rawPath}`) };
  }
  return { image: { name: rawPath.split("/").pop() || "frame.png", mimeType: detected.mimeType, data } };
}

function errorMessageMedia(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function dataUri(mimeType: string, data: Buffer): string {
  return `data:${mimeType};base64,${data.toString("base64")}`;
}

function audioMimeType(format: string): string {
  switch (format.trim().toLowerCase()) {
    case "wav":
      return "audio/wav";
    case "flac":
      return "audio/flac";
    case "pcm":
    case "pcm16":
      return "audio/L16";
    case "mp3":
    default:
      return "audio/mpeg";
  }
}

function videoExtension(mimeType: string): string {
  if (mimeType.includes("webm")) return "webm";
  if (mimeType.includes("quicktime")) return "mov";
  return "mp4";
}

function normalizeDuration(value: unknown): number | undefined {
  if (typeof value !== "number" || !Number.isFinite(value)) return undefined;
  return Math.min(30, Math.max(1, Math.round(value)));
}

function isSuccessStatus(status: string): boolean {
  return ["success", "succeeded", "completed", "complete"].includes(status.trim().toLowerCase());
}

function isFailureStatus(status: string): boolean {
  return ["fail", "failed", "error", "canceled", "cancelled"].includes(status.trim().toLowerCase());
}

function networkErrorMessage(url: string, error: unknown): string {
  const target = url.split("?")[0];
  if (error instanceof DOMException && error.name === "TimeoutError") {
    return `media request to ${target} timed out`;
  }
  if (error instanceof DOMException && error.name === "AbortError") {
    return `media request to ${target} was canceled`;
  }
  return `media request to ${target} failed: ${error instanceof Error ? error.message : String(error)}`;
}

function toolError(code: string, message: string): ToolResult {
  return { output: { error: { code, message } }, isError: true };
}

/**
 * Marker error for vendor (non-OpenAI-compat) provider failures whose message is
 * already operator-facing (an HTTP status+body or a `base_resp` assertion). The
 * execute handlers surface these as `provider_error`; anything else is treated
 * as a transport/`generation_failed` error.
 */
class MediaProviderError extends Error {}

/**
 * POST/GET JSON to a vendor endpoint and parse the body. A non-2xx becomes an
 * {@link ImageGenHttpError} (carrying status + body); a non-JSON 2xx body throws.
 * Faithful to the original `requestJson`.
 */
async function requestJson<T>(url: string, init: RequestInit): Promise<T> {
  const response = await fetch(url, init);
  const text = await response.text();
  if (!response.ok) throw new ImageGenHttpError(response.status, text);
  try {
    return JSON.parse(text) as T;
  } catch {
    throw new Error(`provider returned invalid JSON from ${url.split("?")[0]}`);
  }
}

/** Assert a Async `base_resp.status_code === 0`, else throw its status_msg. */
function assertAsyncOk(baseResp: AsyncBaseResp | undefined, label: string): void {
  const statusCode = baseResp?.status_code;
  if (typeof statusCode === "number" && statusCode !== 0) {
    throw new MediaProviderError(`${label} failed (${statusCode}): ${baseResp?.status_msg ?? "unknown error"}`);
  }
}

/** Decode a whitespace-tolerant hex string into bytes; reject malformed input. */
function bufferFromHex(value: string): Buffer {
  const normalized = value.replace(/\s+/g, "");
  if (!normalized || normalized.length % 2 !== 0 || /[^0-9a-f]/i.test(normalized)) {
    throw new Error("provider returned invalid hex audio data");
  }
  return Buffer.from(normalized, "hex");
}

/** Audio file extension for a normalized format (pcm16 → pcm). */
function audioExtension(format: string): string {
  const normalized = normalizeAudioFormat(format);
  return normalized === "pcm16" ? "pcm" : normalized;
}

function pickString(value: unknown): string | undefined {
  return typeof value === "string" && value.trim() ? value.trim() : undefined;
}

function pickBoolean(value: unknown): boolean | undefined {
  return typeof value === "boolean" ? value : undefined;
}

interface ImagesResponse {
  data?: Array<{ b64_json?: string; url?: string }>;
}

interface AudioResponse {
  data?: Array<{ b64_json?: string; audio?: string; url?: string }>;
  b64_json?: string;
  audio?: string;
  url?: string;
}

interface VideoSubmitResponse {
  task_id?: string;
  id?: string;
  status?: string;
  video_url?: string;
  url?: string;
  b64_json?: string;
  data?: Array<{ url?: string; b64_json?: string }>;
}

// --- Vendor (Async / MiMo) response shapes --------------------------------

interface AsyncBaseResp {
  status_code?: number;
  status_msg?: string;
}

interface AsyncImageResponse {
  base_resp?: AsyncBaseResp;
  data?: { image_base64?: string[]; image_urls?: string[] };
}

interface AsyncAudioResponse {
  base_resp?: AsyncBaseResp;
  data?: { audio?: string };
}

interface MimoSpeechResponse {
  choices?: Array<{ message?: { audio?: { data?: string } } }>;
}

interface AsyncVideoResponse {
  base_resp?: AsyncBaseResp;
  task_id?: string;
  status?: string;
  file_id?: string;
  file?: { download_url?: string };
}
